In [1]:
import numpy as np
print(np.__version__)

2.3.4


In [2]:
arr= np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
array = np.array([
    [['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
    [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']]
])
print(array)

[[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]

 [['S' 'T' 'U']
  ['V' 'W' 'X']
  ['Y' 'Z' ' ']]]


In [4]:
word=array[0,2,2]+array[2,2,2]+array[1,0,2]+array[1,1,2]+array[2,1,0]+ array[0,1,1]+array[2,2,2]+array[2,0,2]
print(word)

I LOVE U


In [5]:
print('The dimension of array is',array.ndim)
print(array.shape) #(3, 3, 3) (3 layers, 3 rows, 3 colums)

The dimension of array is 3
(3, 3, 3)


In [6]:
#how to access, for example if i refer array[1,2,1] that means i choose layer 1,row 2 and cow 1 =>'Q'
print(array[1,2,1])
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

Q
0
1
2
3


In [7]:
e=np.array([1,2,3,4,5], ndmin=3)
print('The dimension of array e is',e.ndim,'because we use ndmin = 3')

The dimension of array e is 3 because we use ndmin = 3


In [8]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]


In [14]:
print(arr[-3:-1])

[5 6]


In [15]:
print(arr[1:5:2])

[2 4]


In [16]:
print(arr[::2])

[1 3 5 7]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [ ]:
print(arr[::-1]) #reverse 

[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [19]:
print(arr[0:2, 2]) #chọn cả 2 hàng và trả về giá trị index=2

[3 8]


In [20]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [28]:
arr= np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14,15]])
print(arr[:,0]) #choose row0->row2 and pick all elements index0= 0

[ 1  6 11]


In [29]:
print(arr[:,::2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]]
