In [4]:
import numpy as np
array = np.array([1.01, 2.02, 3.03])

In [20]:
print(array+1)
print(array-2)
print(array*3)
print(array/4)
print(array ** 5)

[2.01 3.02 4.03]
[-0.99  0.02  1.03]
[3.03 6.06 9.09]
[0.2525 0.505  0.7575]
[  1.05101005  33.6323216  255.39544217]


In [ ]:
print(np.sqrt(array))
print(np.pi)
print(np.round(array)) #np.floor(array)
print(np.ceil(array))# làm tròn lên

[1.00498756 1.42126704 1.74068952]
3.141592653589793
[1. 2. 3.]
[2. 3. 4.]


In [ ]:
#Vectorized math funcs
r=np.array([1,2,3])
print(np.pi*r**2) # S hình tròn

[ 3.14159265 12.56637061 28.27433388]


In [17]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
# np.add(a,b)
print(a-b)
# np.substract(a,b)
print(a*b)
# np.multiply(a,b)
print(a/b)
# np.divide(a,b)
print(a**b)
# np.power(a,b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [29]:
scores=np.array([12,54,23,65,100,34])
print(scores==100)

[False False False False  True False]


In [31]:
print(scores>=30)

[False  True False  True  True  True]


In [32]:
print(scores<60)

[ True  True  True False False  True]


In [34]:
scores[scores>50]=0
print(scores)

[12  0 23  0  0 34]


Mẹo nhớ
Đối với broadcasting, hãy căn hai shape từ bên phải và kiểm tra từng chiều:
✅ Hai kích thước bằng nhau → được.
✅ Một trong hai bằng 1 → được (NumPy sẽ "kéo giãn" chiều đó).
❌ Khác nhau và không có số nào bằng 1 → lỗi.
Với ví dụ của bạn:
(1,4) * (4,1) → được vì cả hai chiều đều có ít nhất một giá trị là 1.
(2,4) * (4,1) → không được vì ở chiều đầu là 2 và 4, không bằng nhau và cũng không có 1.


In [9]:
arr=np.array([[1,2,3,4]]) 
brr=np.array([[1],[2],[3],[4]]) 
print(arr.shape)
print(brr.shape)
print(arr*brr)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [10]:
np.multiply(arr,brr)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [11]:
np.divide(arr,brr)

array([[1.        , 2.        , 3.        , 4.        ],
       [0.5       , 1.        , 1.5       , 2.        ],
       [0.33333333, 0.66666667, 1.        , 1.33333333],
       [0.25      , 0.5       , 0.75      , 1.        ]])

In [6]:
#Broadcasting a 1D Array to a 2D Array
a = np.array([2, 4, 6])
b = np.array([[1, 3, 5], [7, 9, 11]])
res = a + b
print(res)
np.add(a,b)


[[ 3  7 11]
 [ 9 13 17]]


array([[ 3,  7, 11],
       [ 9, 13, 17]])

In [7]:
np.subtract(a,b)

array([[ 1,  1,  1],
       [-5, -5, -5]])

In [38]:
a = np.array([12, 24, 35, 45, 60, 72])
b = np.array(["Adult", "Minor"])
res = np.where(a > 18, b[0], b[1])
print(res)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']
