In [14]:
import numpy as np

In [15]:
x=np.array([i for i in range(10)])
print(x)
x

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.where(x%2,'Even','Odd')

array(['Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even'], dtype='<U4')

In [17]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
condlist=[x<5,x>5]
choicelist=[x**2,x**3]
np.select(condlist,choicelist,default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

if x < 5:
    dùng x**2

elif x > 5:
    dùng x**3

else:
    dùng default
    
np.select khác np.where ở chỗ là nó dùng được nhiều cặp đk

In [19]:
arr=np.array([[1,2,5],[4,9,6],[7,8,3]])
arr

array([[1, 2, 5],
       [4, 9, 6],
       [7, 8, 3]])

In [20]:
np.argmin(arr) #Trả về index giá trị nhỏ nhất

np.int64(0)

In [21]:
np.argmax(arr)

np.int64(4)

In [22]:
np.amin(arr)

np.int64(1)

In [23]:
np.amax(arr)

np.int64(9)

In [24]:
#Lấy giá trị Min từng cột
np.amin(arr,axis=0)

array([1, 2, 3])

In [25]:
#Lấy giá trị Min từng hàng
np.amin(arr,axis=1)

array([1, 4, 3])

In [26]:
#Lấy giá trị Max từng cột
np.amax(arr,axis=0)

array([7, 9, 6])

In [27]:
#Lấy giá trị Max từng hàng
np.amax(arr,axis=1)

array([5, 9, 8])

In [28]:
arr

array([[1, 2, 5],
       [4, 9, 6],
       [7, 8, 3]])

In [42]:
print("Tổng từng giá trị từng cột",np.sum(arr,axis=0))

Tổng từng giá trị từng cột [12 19 14]


In [43]:
print("Tổng từng giá trị từng hàng",np.sum(arr,axis=1))

Tổng từng giá trị từng hàng [ 8 19 18]


In [30]:
print('(1+2+3+..+9)/9 = ',np.mean(arr))


(1+2+3+..+9)/9 =  5.0


In [31]:
np.median(arr)

np.float64(5.0)

In [32]:
np.std(arr)

np.float64(2.581988897471611)

In [33]:
np.var(arr)

np.float64(6.666666666666667)

In [34]:
np.percentile(arr,25)

np.float64(3.0)

Tóm tắt

Hàm	Ý nghĩa	Ví dụ kết quả

np.mean()	

Trung bình cộng	

np.median()

Trung vị(giá trị ở giữa sau khi sắp xếp)

np.std() (Standard Deviation)

Độ lệch chuẩn(mức độ phân tán dữ liệu)	

np.var()

Phương sai (std²) (Variance)

np.percentile(arr, p)

Giá trị tại phân vị p%

50% = median


In [35]:
np.sin(arr*np.pi/180)

array([[0.01745241, 0.0348995 , 0.08715574],
       [0.06975647, 0.15643447, 0.10452846],
       [0.12186934, 0.1391731 , 0.05233596]])

In [36]:
np.cos(arr*np.pi/180)

array([[0.9998477 , 0.99939083, 0.9961947 ],
       [0.99756405, 0.98768834, 0.9945219 ],
       [0.99254615, 0.99026807, 0.99862953]])

In [37]:
np.tan(arr*np.pi/180)

array([[0.01745506, 0.03492077, 0.08748866],
       [0.06992681, 0.15838444, 0.10510424],
       [0.12278456, 0.14054083, 0.05240778]])

In [38]:
np.arcsin(arr*np.pi/180)

array([[0.01745418, 0.03491368, 0.08737761],
       [0.06987   , 0.15773288, 0.1049121 ],
       [0.12247904, 0.14008405, 0.05238383]])

In [39]:
np.arccos(arr*np.pi/180)

array([[1.55334215, 1.53588265, 1.48341872],
       [1.50092632, 1.41306345, 1.46588422],
       [1.44831729, 1.43071228, 1.5184125 ]])

In [40]:
np.arctan(arr*np.pi/180)

array([[0.01745152, 0.03489242, 0.08704595],
       [0.06970008, 0.1558065 , 0.10433946],
       [0.12157057, 0.13872945, 0.05231211]])