In [2]:
import numpy as np

In [5]:
ages=np.array([[16,22,34,41,55],[26,27,28,19,18]])

In [8]:
print(ages[(ages<20) | (ages>40) ])

[16 41 55 19 18]


In [29]:
rng=np.random.default_rng()
print(rng.integers(1,7))

3


In [39]:
print(rng.integers(low=1,high=101))#k tính số 101
print(rng.integers(low=1,high=101,size=4))
print(rng.integers(low=1,high=101,size=(3,2)))

46
[89 95  4 41]
[[25 83]
 [65 96]
 [33 74]]


In [47]:
np.random.seed(seed=1)

In [50]:
print(np.random.uniform(low=-1,high=1,size=(3,2)))

[[-0.5910955   0.75623487]
 [-0.94522481  0.34093502]
 [-0.1653904   0.11737966]]


In [61]:
rng=np.random.default_rng()
fruits=np.array(["apple","banana","coconut","lemon","waterlemon"])
fruit=rng.choice(fruits,size=(3,3))
print(fruit)

[['apple' 'apple' 'lemon']
 ['apple' 'lemon' 'coconut']
 ['apple' 'waterlemon' 'waterlemon']]


In [66]:
arr=np.array([1,2,3,4,5])
rng.shuffle(arr)
print(arr)

[4 1 3 2 5]
